version: "3.5"

name: escamboapp_devcontainer

services:
  # Primary application service
  escamboapp:
    user: "vscode:vscode"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - RUBY_VERSION=${RUBY_VERSION}
        - NODE_JS_VERSION=${NODE_JS_VERSION}
        - BUNDLE_VERSION=${BUNDLE_VERSION}       
    ports:
      - ${APP_MAIN_PORT}:${APP_MAIN_PORT}
    volumes:
      - ..:/app:cached
      - $HOME/.ssh/:/home/vscode/.ssh/
    command: sleep infinity
    networks:
      - escamboapp_network_shared

  # PostgreSQL database service
  postgres:
    image: postgres:12-alpine
    env_file:
      - path: ./postgres_devcontainer.env
        required: true    
    volumes:
      - escamboapp_postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - escamboapp_network_shared
  
  # Mailcatcher service
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - ${MAIL_CATCHER_PORT}:1080
    networks:
      - escamboapp_network_shared

volumes:
  escamboapp_postgres_data:
    driver: local

networks:
  escamboapp_network_shared:
    external: true
    name: escamboapp_network_shared
